var args = process.argv.slice(2);
if(args[0] == "-test"){
  console.log("Debug mode activated")
}
console.clear()
console.log("                                                      .                         ")
console.log("                                                   ...                          ")
console.log("                                                   ..                           ")
console.log("                                            ..     ...                          ")
console.log("                             ........ .                                         ")
console.log("                     ..         .            .      .       .                   ")
console.log("                     ,.            . . ..     ... ..                            ")
console.log("                    ..            ..... ,. . .  . .    ..                       ")
console.log("                   ..           ............ .    ,               ..            ")
console.log("                    .   .         .. ...... . .....            ...              ")
console.log("                            ................... ..             ..               ")
console.log("                      ................,,,.... ..,             ..      ..        ")
console.log("                 ......,............. ......   . .       .  .. .      .         ")
console.log("              .. . .....  .....,...           . ,......     . ..                ")
console.log("              . ..         . ......        ..   .,....   ......         ..      ")
console.log("            . ..           ..  ..   ....  .,,,,..........     .  .. .. ..       ")
console.log("              ..        .  . ... .   . ...,.. ............                      ")
console.log("               .      .... ,......  . ........... . ....          . . ......    ")
console.log("                   ..........  ....... .     . .  ..,...          .      .      ")
console.log("              ......... ......  . ... .    .   ..       ..       ......         ")
console.log("          . ..... .... ....      . .         .  .  ..     ..........   .        ")
console.log("           ...........           . .           ... .   . ..... .. .             ")
console.log("         .  ......        .       ..            .. .  .         . .             ")
console.log("            .... .          . ......                .......                     ")
console.log("                           . .......                 .  .                       ")
console.log("                             ...   .                                            ")
console.log("                              ...                                               ")
console.log("                                .                                               ")

